name: test github actions

on:
  push:
    branches:
      - master

env:
  workflowsEnv: workflowsEnv

jobs: 
  # 环境准备
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    # env:
    #   TO_EMAIL_ACCOUNT: null
    outputs:
      TO_EMAIL_ACCOUNT: ${{ steps.get-email.outputs.TO_EMAIL_ACCOUNT }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install package
        run: npm install
      - name: get email
        id: get-email
        run: |
          TO_EMAIL_ACCOUNT="$(git log | grep -o -m 1 '<.*>' | grep -o '[^<].*[^>]')"
          echo "::set-output name=TO_EMAIL_ACCOUNT::$TO_EMAIL_ACCOUNT"
      - name: build
        run: npm run build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN: 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
          # GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: waterguan/waterguan.github.io
          GIT_CONFIG_NAME: waterguan
          GIT_CONFIG_EMAIL: 136087767@qq.com
          BRANCH: page
          FOLDER: build
  
  # github actions结果通知
  notice-messge:
    name: notify the user of the result
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - name: send email
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com # 邮件地址
          server_port: 465 # smtp端口号
          username: ${{ secrets.FROM_EMAIL_ACCOUNT }}
          password: ${{ secrets.FROM_EMAIL_AUTH_CODE }}
          subject: GHA result
          body: GHA Success
          to: ${{ needs.build-and-deploy.outputs.TO_EMAIL_ACCOUNT }} # 目的邮箱
          from: ${{ secrets.FROM_EMAIL_ACCOUNT }}
