# workflows名字
name: test github actions

# 触发的事件
on:
  push:
    branches:
      - master

# 环境变量
env:
  workflowsEnv: workflowsEnv

jobs: 
  # 环境准备
  build-and-deploy:
    name: build and deploy # job名
    runs-on: ubuntu-latest # 虚拟主机
    outputs:
      TO_EMAIL_ACCOUNT: ${{ steps.get-email.outputs.TO_EMAIL_ACCOUNT }}
    steps:
      # 代码拉取
      - name: checkout
        uses: actions/checkout@master
      
      # 安装nonde
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      # 安装依赖包
      - name: install package
        run: npm install

      # 获取email地址
      - name: get email
        id: get-email
        run: |
          TO_EMAIL_ACCOUNT="$(git log | grep -o -m 1 '<.*>' | grep -o '[^<].*[^>]')"
          echo "::set-output name=TO_EMAIL_ACCOUNT::$TO_EMAIL_ACCOUNT"
      
      # 构建
      - name: build
        run: npm run build
      
      # 发布
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 本仓库需要个人访问令牌
          BRANCH: page # 目标branch
          FOLDER: build # 当前资源所在文件夹
  
  # github actions结果通知
  notice-messge:
    name: notify the user of the result
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      # 给push者发送部署成功邮件
      - name: send email
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com # 邮件地址
          server_port: 465 # smtp端口号
          username: ${{ secrets.FROM_EMAIL_ACCOUNT }} # 发件邮箱
          password: ${{ secrets.FROM_EMAIL_AUTH_CODE }} # 授权码
          subject: GHA result
          body: GHA Success # 邮件内容
          to: ${{ needs.build-and-deploy.outputs.TO_EMAIL_ACCOUNT }} # 收件邮箱
          from: ${{ secrets.FROM_EMAIL_ACCOUNT }}
