name: test github actions

on: [push]

env:
  workflowsEnv: workflowsEnv

jobs: 
  # 环境准备
  prepare:
    name: prepare environment
    runs-on: ubuntu-latest
    # env:
    #   TO_EMAIL_ACCOUNT: null
    outputs:
      TO_EMAIL_ACCOUNT: ${{ steps.get-email.outputs.TO_EMAIL_ACCOUNT }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install package
        run: npm install
      - name: get email
        id: get-email
        run: |
          TO_EMAIL_ACCOUNT="$(git log | grep -o -m 1 '<.*>' | grep -o '[^<].*[^>]')"
          echo "::set-output name=TO_EMAIL_ACCOUNT::$TO_EMAIL_ACCOUNT"
      - name: build
        run: npm run build
      # - name: email notification
      #   uses: 
      - name: exit
        env:
          stepEnv: stepEnv
        if: ${{ env.stepEnv == 'stepEnv' }}
        run: |
          echo just test $stepEnv $GITHUB_REF $GITHUB_ACTOR
  
  # github actions结果通知
  notice-messge:
    name: notify the user of the result
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: send email
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com
          server_port: 465
          username: ${{ secrets.FROM_EMAIL_ACCOUNT }}
          password: ${{ secrets.FROM_EMAIL_AUTH_CODE }}
          subject: GHA result
          body: GHA Success
          to: ${{ needs.prepare.outputs.TO_EMAIL_ACCOUNT }}
          from: ${{ secrets.FROM_EMAIL_ACCOUNT }}
  # test:
  #   name: test something
  #   setps:
  #     - name: print
  #       run: echo another job