# workflows名字
name: test github actions

# 触发的事件
on:
  push:
    branches:
      - master

# 环境变量
env:
  workflowsEnv: workflowsEnv

jobs: 
  # 环境准备
  job1:
    name: build and deploy # job名
    runs-on: ubuntu-latest # 虚拟主机
    
    steps:
      # 代码拉取
      - name: checkout
        uses: actions/checkout@master
      
      # 安装nonde
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      # 安装依赖包
      - name: install package
        run: npm install
  
  # job2打印信息
  job2:
    name: this is job2
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      # 给push者发送部署成功邮件
      - name: print info
        run: echo jobs
